version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/auth_db
      SECRET_KEY: your-super-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
